Multiworld support
cuberite/MagicCarpet pull request #3
Opened 2017-02-23 12:18 UTC by mathiascode

Carpets now work in different worlds.

2017-02-23 12:38 UTC, madmaxoft requested changes

2017-02-23 12:38 UTC, madmaxoft commented on LICENSE
> +                                 Apache License
I think the license should be added in a separate commit, in a separate PR.

2017-02-23 19:09 UTC, mathiascode commented on LICENSE
> +                                 Apache License
I've removed the license file from this PR.

2017-02-23 22:14 UTC, madmaxoft approved these changes

2017-02-25 09:27 UTC, merged

2017-02-25 09:28 UTC, madmaxoft commented
Now add the license in a separate PR :)